# Generated by Django 6.1 on 2026-08-11 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateTimeField()),
                ('machine', models.CharField(max_length=100)),
                ('operator1', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PDDResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.FloatField()),
                ('p80', models.FloatField(default=0)),
                ('p90', models.FloatField(default=0)),
                ('ptpr', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.pddsession')),
            ],
        ),
    ]
